version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: necrasovka-backend
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
    networks:
      - necrasovka-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: necrasovka-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - necrasovka-network

networks:
  necrasovka-network:
    driver: bridge
